module.exports = [
    {
        src:[
            './build/js/plugin/**',
            './build/js/common/**',
            './build/validate/validate.js',
        ],
        concatName:'main.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/admin/admin.js'
        ],
        concatName:'admin-admin.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/admin/merchant.js'
        ],
        concatName:'admin-merchant.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/validate/sub/merchant.js',
            './build/js/page/merchant/add.js'
        ],
        concatName:'merchant-add.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/validate/sub/merchant.js',
            './build/validate/sub/rule.js',
            './build/js/ui/swiper.min.js',
            './build/js/ui/file.js',
            './build/js/ui/qrcode.js',
            './build/js/ui/date-picker.js',
            './build/js/ui/web-socket.js',
            './build/js/page/merchant/index.js',
            './build/js/page/merchant/extend/**'
        ],
        concatName:'merchant-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/swiper.min.js',
            './build/js/ui/qrcode.js',
            './build/js/ui/user/count.js',
            './build/js/page/user/index.js',
            './build/js/page/user/extend/**'
        ],
        concatName:'user-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/merchant/member.js',
        ],
        concatName:'merchant-member.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/swiper.min.js',
            './build/js/ui/date-time.js',
            './build/js/ui/qrcode.js',
            './build/js/ui/web-socket.js',
            './build/js/page/game/lottery/common.js',
            './build/js/page/game/lottery/index.js',
            './models/use-js-common/game.js',
        ],
        concatName:'game-lottery-index.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './models/use-js-common/game.js',
            './build/js/page/game/detail.js',
        ],
        concatName:'game-detail.js',
        destPath:'./build/js/build/'
    },
];