module.exports = function(rule){
  rule.lottery = {
        bet:{
            betMaxCount:20,
            betMinScore:500,
            betMaxScore:2000,
            betAllMaxScore:20000,
            rebateRate:1.5,
            minRebateScore:0,
            maxRebateScore:300000,
            childRebateRate:0.5,
            childMinRebateScore:0,
            childMaxRebateScore:300000,
        },
        res:[
            {
                name:'大',
                code:'big',
                type:3,
                rate:1.95
            },
            {
                name:'小',
                code:'small',
                type:3,
                rate:1.95
            },
            {
                name:'单',
                code:'odd',
                type:3,
                rate:1.95
            },
            {
                name:'双',
                code:'even',
                type:3,
                rate:1.95
            },
            {
                name:'龙',
                code:'long',
                type:3,
                rate:1.95
            },
            {
                name:'虎',
                code:'hu',
                type:3,
                rate:1.95
            },
            {
                name:'和',
                code:'he',
                type:3,
                rate:8
            },
            {
                name:'大单',
                code:'bigOdd',
                type:4,
                rate:3.8
            },
            {
                name:'大双',
                code:'bigEven',
                type:4,
                rate:3.8
            },
            {
                name:'小单',
                code:'smallOdd',
                type:4,
                rate:3.8
            },
            {
                name:'小双',
                code:'smallEven',
                type:4,
                rate:3.8
            },
            {
                name:'单码x1',
                code:'group_1',
                count:1,
                type:1,
                rate:2
            },
            {
                name:'单码x2',
                code:'group_1',
                count:2,
                type:1,
                rate:3
            },
            {
                name:'单码x3',
                code:'group_1',
                count:3,
                type:1,
                rate:5
            },
            {
                name:'单码x4',
                code:'group_1',
                count:4,
                type:1,
                rate:12
            },
            {
                name:'单码x5',
                code:'group_1',
                count:5,
                type:1,
                rate:20
            },
            {
                name:'连码2',
                code:'group_2',
                type:1,
                rate:3
            },
            {
                name:'连码3',
                code:'group_3',
                type:1,
                rate:12
            },
            {
                name:'连码4',
                code:'group_4',
                type:1,
                rate:40
            },
            {
                name:'连码5',
                code:'group_5',
                type:1,
                rate:100
            }
            ,
            {
                name:'定选1',
                code:'select_1',
                type:1,
                rate:9
            },
            {
                name:'定选2',
                code:'select_2',
                type:1,
                rate:30
            },
            {
                name:'定选3',
                code:'select_3',
                type:1,
                rate:100
            },
            {
                name:'定选4',
                code:'select_4',
                type:1,
                rate:200
            },
            {
                name:'定选5',
                code:'select_5',
                type:1,
                rate:500
            },
            {
                name:'定大',
                code:'selectBig',
                type:5,
                rate:1.95
            },
            {
                name:'定小',
                code:'selectSmall',
                type:5,
                rate:1.95
            },
            {
                name:'定单',
                code:'selectOdd',
                type:5,
                rate:1.95
            },
            {
                name:'定双',
                code:'selectEven',
                type:5,
                rate:1.95
            },
        ],
        withdraw:{
            min:10000,
            max:100000
        }
  };
};